# Generated by Django 5.2.5 on 2026-04-15 10:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Номер уровня')),
                ('base_cost', models.BigIntegerField(default=1000, verbose_name='Базовая стоимость создания')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название нации')),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flags/', verbose_name='Флаг')),
            ],
            options={
                'verbose_name': 'Нация',
                'verbose_name_plural': 'Нации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Crewman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.BigIntegerField(default=1000, verbose_name='Кредиты')),
                ('garage_slots', models.IntegerField(default=3, verbose_name='Мест в ангаре')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crewman', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Член экипажа',
                'verbose_name_plural': 'Члены экипажа',
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название танка')),
                ('is_in_battle', models.BooleanField(default=False, verbose_name='В бою')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='tanks.level')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='tanks.nation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='tanks.crewman')),
            ],
            options={
                'verbose_name': 'Танк',
                'verbose_name_plural': 'Танки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pending', 'Ожидание'), ('victory', 'Победа'), ('defeat', 'Поражение')], default='pending', max_length=20, verbose_name='Результат')),
                ('reward_earned', models.BigIntegerField(default=0, verbose_name='Полученная награда')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('crewman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='tanks.crewman')),
                ('battle_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='tanks.level')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='tanks.tank')),
            ],
            options={
                'verbose_name': 'Запись о сражении',
                'verbose_name_plural': 'Записи о сражениях',
                'ordering': ['-started_at'],
            },
        ),
    ]
