# Generated by Django 5.2.5 on 2026-04-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='images/flags/', verbose_name='Флаг'),
        ),
    ]
