# Generated by Django 5.2.5 on 2026-04-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0002_alter_nation_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewman',
            name='totp_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/tanks/', verbose_name='Изображение танка'),
        ),
    ]
