# Generated by Django 5.2.5 on 2026-04-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0003_crewman_totp_key_tank_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='base_cost',
        ),
    ]
